mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "my_chat"
log:
  level: "debug"
  filename: "./logs/server.log"
  max_size: 10
  max_age: 30
  max_backups: 5
  compress: true
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 100
kafka:
  addr: "localhost:9092"
  topic: "chat_messages"
  group: "chat_consumer_group"